const MONGODB_USERNAME = process.env.MONGODB_USERNAME;
const MONGODB_PASSWORD = process.env.MONGODB_PASSWORD;
const SESSIONS_SECRET = process.env.SESSIONS_SECRET;

export { MONGODB_USERNAME, MONGODB_PASSWORD, SESSIONS_SECRET };
