const MONGODB_USERNAME = "jleonardi";
const MONGODB_PASSWORD = "CQt0ftOhHqzCNUgi";
const SESSIONS_SECRET =
  "GSN91Ol+26p5KGKr+vzZLfV99m8uHTFEGJSYuw3M4BSld/EX7oZgrqrx8yFnHqM+RAHjhdpo5KgkRfdx+Bxjkw==";

export { MONGODB_USERNAME, MONGODB_PASSWORD, SESSIONS_SECRET };
